service: heutejournal

frameworkVersion: '3'

custom:
  stage: ${opt:stage}
  dev: 
    domainName: dev.${self:service}.sillium.xyz
  prod:
    domainName: ${self:service}.sillium.xyz
  wsgi:
    app: app.app
  pythonRequirements:
    pythonBin: python3

provider:
  name: aws
  runtime: python3.8
  stage: ${self:custom.stage}
  lambdaHashingVersion: '20201221'
  region: eu-central-1

functions:
  getStartTime:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: GET
      - http:
          path: /{proxy+}
          method: GET

plugins:
  - serverless-wsgi
  - serverless-python-requirements
